// todolist-angular/src/app/components/add-todo/add-todo.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Store, select } from '@ngrx/store';
import { TodoListModel } from 'src/app/models/todoList.model';
import { SubmitTodo, InputChanged, UndeleteTodo } from 'src/app/actions/todo.action';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.scss']
})
export class AddTodoComponent implements OnInit {

  form: FormGroup;
  disableAddTodo: boolean = false;
  disableUndelete: boolean = true;
  todoList$: Observable<any>;

  constructor(
    private store: Store<TodoListModel>,
    private formBuilder: FormBuilder,
  ) {
    this.todoList$ = store.pipe(select(state => state));
  }

  ngOnInit() {
    this.form = this.formBuilder.group({
      todoInput: ['']
    });
  }

  submitForm() {
    if (this.form.value.todoInput) {
      this.store.dispatch(SubmitTodo(this.form.value.todoInput));
    }
    console.log('this.form.value.todoInput',this.form.value.todoInput)
  }

  inputChanged() {
    this.store.dispatch(InputChanged(this.form.value.todoInput));
  }

  undelete() {
    this.store.dispatch(UndeleteTodo());
  }

}

<div>
  <form [formGroup]="form"
    (ngSubmit)="submitForm()"
  >
    <input
      class="todo-input"
      formControlName="todoInput"
      (keyup)="inputChanged()"
      placeholder="o que devo fazer?"
    />

    <button
      type="submit"
      class="todo-submit"
      [disabled]="(todoList$ | async).todoList.disableAddTodo"
    >
      Adicionar
    </button>

    <button
      class="todo-undelete"
      (click)="undelete()"
      [disabled]="(todoList$ | async).todoList.disableUndelete"
    >
      Desfazer
    </button>

  </form>
</div>

// todolist-react/src/components/addTodo/index.js
import React from 'react';
import PropTypes from 'prop-types';

const AddTodo = ({ submitTodo, undeleteTodo, inputChanged, disableAddTodo, disableUndelete }) => {
  let input;

  return (
    <div>
      <form
        onSubmit={(event) => {
          event.preventDefault();
          submitTodo(input.value);
          input.value = '';
        }}
      >

        <input
          className="todo-input"
          ref={(element) => {
            input = element;
          }}
          onChange={() => inputChanged(input.value)}
          placeholder="o que devo fazer?"
        />

        <button
          type="submit"
          className="todo-submit"
          disabled={disableAddTodo}
        >
          Adicionar
        </button>

        <button
          className="todo-undelete"
          onClick={() => undeleteTodo()}
          disabled={disableUndelete}
        >
          Desfazer
        </button>

      </form>
    </div>
  );
};

AddTodo.propTypes = {
  submitTodo: PropTypes.func.isRequired,
  undeleteTodo: PropTypes.func.isRequired,
  inputChanged: PropTypes.func.isRequired,
  disableAddTodo: PropTypes.bool.isRequired,
  disableUndelete: PropTypes.bool.isRequired,
};

export default AddTodo;
